=== AlexKeks/JD1/BookDateBase/bin/printedEditionsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/printedEditionsSchema"
	xmlns:tns="http://www.example.org/printedEditionsSchema"
	elementFormDefault="qualified">

	<xs:element name="papers" type="tns:papres_type" />

	<xs:complexType name="papres_type">
		<xs:sequence>
			<xs:element name="book" type="tns:book_type" minOccurs="0"
				maxOccurs="unbounded" />
			<xs:element name="journal" type="tns:journal_type"
				minOccurs="0" maxOccurs="unbounded" />
			<xs:element name="newspaper" type="tns:newspaper_type"
				minOccurs="0" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="paper_type">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" />
	</xs:complexType>

	<xs:complexType name="book_type">
		<xs:complexContent>
			<xs:extension base="tns:paper_type">
				<xs:sequence>
					<xs:element name="autor" type="xs:string" />
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>

	<xs:complexType name="journal_type">
		<xs:sequence>
			<xs:element name="title" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
			<xs:element name="month" type="xs:string" />
		</xs:sequence>

	</xs:complexType>

	<xs:complexType name="newspaper_type">
		<xs:sequence>
			<xs:element name="month" type="xs:string" />
			<xs:element name="pages" type="xs:int" />
			<xs:element name="circulation" type="xs:int" />
		</xs:sequence>

	</xs:complexType>

</xs:schema>

=== AlexKeks/JD1/BookDateBase/XMLDocs/printedEditions.xml
<?xml version="1.0" encoding="UTF-8"?>

<papers xmlns="http://www.it-academy.by/librÐ³arySchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.it-academy.by/printedEditionsSchema printedEditionsSchema.xsd">

	<book id="1">
		<title>Book1</title>
		<pages>100</pages>
		<autor>Autor1</autor>
	</book>
	<book id="2">
		<title>Book2</title>
		<pages>200</pages>
		<autor>Autor2</autor>
	</book>

	<journal number="1">
		<title>Journal1</title>
		<pages>11</pages>
		<month>June</month>
	</journal>
	<journal number="2">
		<title>Journal2</title>
		<pages>22</pages>
		<month>July</month>
	</journal>

	<newspaper number="1">
		<month>January</month>
		<pages>10</pages>
		<circulation>1000</circulation>
	</newspaper>
	<newspaper number="2">
		<month>February</month>
		<pages>20</pages>
		<circulation>2000</circulation>
	</newspaper>

</papers>
